/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moon.projectx.UI.AddAndEditUI;

import javax.swing.JOptionPane;
import moon.projectx.driver.ConnectionDataBase;
import moon.projectx.driver.RequestDataBase;
import moon.projectx.objectTable.DiscountCard;

/**
 *
 * @author alex
 */
public class AddDiscountCardUI extends javax.swing.JFrame {
    ConnectionDataBase connectionDataBase = new ConnectionDataBase();
    RequestDataBase requestDataBase;
    DiscountCard discountCard;
    /**
     * Creates new form AddDiscountCardUI
     */
    public AddDiscountCardUI() {
        initComponents();
        connectionDataBase.connect();
        requestDataBase = new RequestDataBase(connectionDataBase.getConnection());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        percentDiscountCardTextField = new javax.swing.JTextField();
        exitButton = new javax.swing.JButton();
        addDiscountCardButton = new javax.swing.JButton();
        label11 = new javax.swing.JLabel();
        nameDiscountCardTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Відсоток знижки");

        jLabel2.setText("Меню знижок ");

        percentDiscountCardTextField.setText("25");

        exitButton.setText("Вихід");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        addDiscountCardButton.setText("Добавити");
        addDiscountCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDiscountCardButtonActionPerformed(evt);
            }
        });

        label11.setText("Імя");

        nameDiscountCardTextField.setText("someName");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label11)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2))
                            .addComponent(jLabel1))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(percentDiscountCardTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameDiscountCardTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(addDiscountCardButton, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addGap(41, 41, 41)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label11)
                    .addComponent(nameDiscountCardTextField))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(percentDiscountCardTextField))
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addDiscountCardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_exitButtonActionPerformed

    private void addDiscountCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDiscountCardButtonActionPerformed
        
        int tmp = 0;
        try {
            tmp = Integer.valueOf(percentDiscountCardTextField.getText());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Неправильний формат знижки (Потрібно лише цілі числа)");
        }
        
        if(tmp >= 100){
                JOptionPane.showMessageDialog(null, "Знижка не має бути більше або рівна 100");
        } else {
            discountCard = new DiscountCard();
            discountCard.setName(nameDiscountCardTextField.getText());
            discountCard.setPercent(Integer.valueOf(percentDiscountCardTextField.getText()));
            if(requestDataBase.addDiscountCard(discountCard) == true) {
                JOptionPane.showMessageDialog(null, "Додано нову знижкову картку");
                this.dispose();
            }else {
                JOptionPane.showMessageDialog(null, "Щось пішло не так");
            }
        }
        
    }//GEN-LAST:event_addDiscountCardButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDiscountCardButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label11;
    private javax.swing.JTextField nameDiscountCardTextField;
    private javax.swing.JTextField percentDiscountCardTextField;
    // End of variables declaration//GEN-END:variables
}
