/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moon.projectx.UI.AddAndEditUI;
import javax.swing.JOptionPane;
import moon.projectx.driver.ConnectionDataBase;
import moon.projectx.driver.RequestDataBase;
import moon.projectx.objectTable.DiscountCard;
/**
 *
 * @author alex
 */
public class EditDiscountCardUI extends javax.swing.JFrame {
    ConnectionDataBase connectionDataBase = new ConnectionDataBase();
    RequestDataBase requestDataBase;
    DiscountCard discountCard = new DiscountCard();
    
    public EditDiscountCardUI(){
        
    }
    
    public EditDiscountCardUI(DiscountCard discountCard) {
        nameDiscountCardTextField.setText(discountCard.getName());
        percentDiscountCardTextField.setText(String.valueOf(discountCard.getPercent()));
        this.discountCard.setId(discountCard.getId());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameDiscountCardTextField = new javax.swing.JTextField();
        label11 = new javax.swing.JLabel();
        addDiscountCardButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        percentDiscountCardTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Відсоток знижки");

        nameDiscountCardTextField.setText("someName");

        label11.setText("Імя");

        addDiscountCardButton.setText("Зберегти");
        addDiscountCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDiscountCardButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Вихід");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        percentDiscountCardTextField.setText("25");

        jLabel2.setText("Меню знижок ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label11)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2))
                            .addComponent(jLabel1))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(percentDiscountCardTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameDiscountCardTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addDiscountCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label11)
                    .addComponent(nameDiscountCardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(percentDiscountCardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(addDiscountCardButton))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addDiscountCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDiscountCardButtonActionPerformed
        ConnectionDataBase connectionDataBase = new ConnectionDataBase();
        connectionDataBase.connect();
        RequestDataBase requestDataBase = new RequestDataBase(connectionDataBase.getConnection());
        int tmp = 0;
        try {
            tmp = Integer.valueOf(percentDiscountCardTextField.getText());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Неправильний формат знижки (Потрібно лише цілі числа)");
        }

        if(tmp >= 100){
            JOptionPane.showMessageDialog(null, "Знижка не має бути більше або рівна 100");
        } else {
            
            discountCard.setName(nameDiscountCardTextField.getText());
            discountCard.setPercent(Integer.valueOf(percentDiscountCardTextField.getText()));
            
            if(requestDataBase.updateDiscountCard(discountCard.getId(), discountCard) == true) {
                JOptionPane.showMessageDialog(null, "Додано нову знижкову картку");
                this.dispose();
            }else {
                JOptionPane.showMessageDialog(null, "Щось пішло не так");
            }
        }

    }//GEN-LAST:event_addDiscountCardButtonActionPerformed

    public  void sendDiscountCard(DiscountCard discountCard) {
        initComponents();
        this.discountCard = discountCard;
        nameDiscountCardTextField.setText(discountCard.getName());
        percentDiscountCardTextField.setText(String.valueOf(discountCard.getPercent()));
        this.discountCard.setId(discountCard.getId());
        
        
    } 
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_exitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDiscountCardButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label11;
    private javax.swing.JTextField nameDiscountCardTextField;
    private javax.swing.JTextField percentDiscountCardTextField;
    // End of variables declaration//GEN-END:variables
}
