/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package moon.projectx.UI;

import javax.swing.JOptionPane;
import moon.projectx.UI.SettingUI;
import moon.projectx.objectTable.User;
import moon.projectx.driver.ConnectionDataBase;
import moon.projectx.driver.RequestDataBase;
import moon.projectx.SettingAndUser;

/**
 *
 * @author user
 */
public class LoginUI extends javax.swing.JFrame {
    
    
    ConnectionDataBase connectionDataBase = new ConnectionDataBase();
    RequestDataBase requestDataBase;
    User user = new User();
    SettingUI settingUI = new SettingUI();
    
    
    
    
    /**
     * Creates new form LoginUI
     */
    public LoginUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EnterButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        loginTextField = new javax.swing.JTextField();
        passwordPasswordField = new javax.swing.JPasswordField();
        exitButton = new javax.swing.JButton();
        settingButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(555, 350));
        setMinimumSize(new java.awt.Dimension(555, 350));
        setResizable(false);

        EnterButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EnterButton.setText("Увійти");
        EnterButton.setPreferredSize(new java.awt.Dimension(110, 30));
        EnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleLabel.setText("Ласкаво Просимо");
        titleLabel.setToolTipText("");
        titleLabel.setName("titleLabel"); // NOI18N

        loginLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginLabel.setText("Логін");

        passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordLabel.setText("Пароль");

        loginTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginTextField.setToolTipText("");

        passwordPasswordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        exitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exitButton.setText("Вихід");
        exitButton.setPreferredSize(new java.awt.Dimension(110, 30));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        settingButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        settingButton.setText("Налаштування");
        settingButton.setPreferredSize(new java.awt.Dimension(110, 30));
        settingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                        .addGap(182, 182, 182))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(settingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(loginTextField)
                                    .addComponent(passwordPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EnterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel)
                    .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterButtonActionPerformed
        
        connectionDataBase.connect();
        requestDataBase = new RequestDataBase(connectionDataBase.getConnection());
        int dataLogin       = requestDataBase.getUserLogin(loginTextField.getText());
        int dataPassword    = requestDataBase.getUserPassword(passwordPasswordField.getText());
        
        if(dataLogin == 1 && dataPassword == 1) {
            
//            JOptionPane.showMessageDialog(null, "You enter");
             
            
            User u = new User();
            int tmp = requestDataBase.getUserId(loginTextField.getText());
            u = requestDataBase.getUser(tmp);
            SettingAndUser.User.userName = u.getName();
            SettingAndUser.User.userLastName = u.getLastName();
            
            int userType = requestDataBase.getUserType(loginTextField.getText());
            
            if(userType == 0){
                new MainMenuAdminUI().setVisible(rootPaneCheckingEnabled);
                this.dispose();
            }else if(userType == 1) {
                new MainMenuUserUI().setVisible(rootPaneCheckingEnabled);
                this.dispose();
            }
        }else if(dataLogin != 1 && dataPassword != 1) {
            JOptionPane.showMessageDialog(null, "Wrong login and password");
        }else if(dataLogin != 1) {
            JOptionPane.showMessageDialog(null, "Wrong login");
        }else if(dataPassword != 1) {
            JOptionPane.showMessageDialog(null, "Wrong password");
        }            
    }//GEN-LAST:event_EnterButtonActionPerformed

    private void settingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingButtonActionPerformed
        
        settingUI.setVisible(rootPaneCheckingEnabled);
        
    }//GEN-LAST:event_settingButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnterButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordPasswordField;
    private javax.swing.JButton settingButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
