/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moon.projectx.UI;

import javax.swing.JOptionPane;
import moon.projectx.objectTable.Merch;
import moon.projectx.UI.TableModel.MerchTableModel;
import moon.projectx.driver.ConnectionDataBase;
import moon.projectx.driver.RequestDataBase;
import moon.projectx.UI.SaleFormUI;

public class SaleMenuUI extends javax.swing.JFrame {
    
    ConnectionDataBase connectionDataBase = new ConnectionDataBase();
    RequestDataBase requestDataBase;
    MerchTableModel merchTableModel = new MerchTableModel();
    Merch merch = new Merch();
    SaleFormUI saleFormUI;
    
    public SaleMenuUI() {
        
        initComponents();
        
        connectionDataBase.connect();
        requestDataBase = new RequestDataBase(connectionDataBase.getConnection());
        
        pricebuttonGroup.add(priceBilsheRadioButton);
        pricebuttonGroup.add(priceMensheRadioButton);
        
        countbuttonGroup.add(countBilsheRadioButton);
        countbuttonGroup.add(countMensheRadioButton);
        
        categoryList.setModel(requestDataBase.getNameCategory());
        
        table.setModel(merchTableModel);
        merchTableModel.refreshData(requestDataBase.getAllMerch());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pricebuttonGroup = new javax.swing.ButtonGroup();
        countbuttonGroup = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        searchButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        priceBilsheRadioButton = new javax.swing.JRadioButton();
        priceMensheRadioButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        countMensheRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        categoryList = new javax.swing.JList<>();
        clearFilterButton = new javax.swing.JButton();
        saleButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        countBilsheRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        jLabel6.setText("Меню продаж");

        jLabel1.setText("Пошук по назві товара");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(table);

        searchButton.setText("Пошук");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Ціна");

        priceBilsheRadioButton.setText("Більше");
        priceBilsheRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceBilsheRadioButtonActionPerformed(evt);
            }
        });

        priceMensheRadioButton.setText("Менше");
        priceMensheRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceMensheRadioButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Кількість");

        countMensheRadioButton.setText("Менше");
        countMensheRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countMensheRadioButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Категорія");

        categoryList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        categoryList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        categoryList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                categoryListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(categoryList);

        clearFilterButton.setText("Скинути фільтр");
        clearFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFilterButtonActionPerformed(evt);
            }
        });

        saleButton.setText("Продажа");
        saleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Вийти");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        countBilsheRadioButton.setText("Більше");
        countBilsheRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countBilsheRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(priceMensheRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(priceBilsheRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clearFilterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(saleButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(countMensheRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(countBilsheRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceMensheRadioButton)
                            .addComponent(priceBilsheRadioButton))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(countMensheRadioButton)
                            .addComponent(countBilsheRadioButton))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearFilterButton)
                        .addGap(18, 18, 18)
                        .addComponent(saleButton)
                        .addGap(18, 18, 18)
                        .addComponent(exitButton)
                        .addContainerGap(23, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        if(!searchTextField.getText().equals("")){
            
            connectionDataBase.connect();
            requestDataBase = new RequestDataBase(connectionDataBase.getConnection());
            
            merchTableModel = new MerchTableModel();
            table.setModel(merchTableModel);
            merchTableModel.refreshData(requestDataBase.getAllMerchSerch(searchTextField.getText()));
            
        }else JOptionPane.showMessageDialog(null, "Поле пошуку пусте");
    }//GEN-LAST:event_searchButtonActionPerformed

    private void clearFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFilterButtonActionPerformed
            
            
            searchTextField.setText("");
            
            pricebuttonGroup.clearSelection();
            countbuttonGroup.clearSelection();
            categoryList.clearSelection();
            table.clearSelection();
            
            connectionDataBase.connect();
            requestDataBase = new RequestDataBase(connectionDataBase.getConnection());
            
            merchTableModel = new MerchTableModel();
            table.setModel(merchTableModel);
            merchTableModel.refreshData(requestDataBase.getAllMerch());
    }//GEN-LAST:event_clearFilterButtonActionPerformed

    private void categoryListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_categoryListValueChanged
        
            connectionDataBase.connect();
            requestDataBase = new RequestDataBase(connectionDataBase.getConnection());
            
            merchTableModel = new MerchTableModel();
            table.setModel(merchTableModel);
            merchTableModel.refreshData(requestDataBase.getAllMerchCategory(categoryList.getSelectedValue()));
    }//GEN-LAST:event_categoryListValueChanged

    private void priceMensheRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceMensheRadioButtonActionPerformed
        
        if(priceMensheRadioButton.isSelected()){
            
            connectionDataBase.connect();
            requestDataBase = new RequestDataBase(connectionDataBase.getConnection());
            
            merchTableModel = new MerchTableModel();
            table.setModel(merchTableModel);
            merchTableModel.refreshData(requestDataBase.getAllMerchPriceASC());
            
        } else if(priceMensheRadioButton.isSelected() && countMensheRadioButton.isSelected()) {
            
            connectionDataBase.connect();
            requestDataBase = new RequestDataBase(connectionDataBase.getConnection());
            
            merchTableModel = new MerchTableModel();
            table.setModel(merchTableModel);
            merchTableModel.refreshData(requestDataBase.getAllMerchPriceDescAndCountAsc());
            
        } else if (priceMensheRadioButton.isSelected() && countBilsheRadioButton.isSelected()) {
            
            connectionDataBase.connect();
            requestDataBase = new RequestDataBase(connectionDataBase.getConnection());
            
            merchTableModel = new MerchTableModel();
            table.setModel(merchTableModel);
            merchTableModel.refreshData(requestDataBase.getAllMerchPriceASCandCountDESC());
        }
    }//GEN-LAST:event_priceMensheRadioButtonActionPerformed

    private void priceBilsheRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceBilsheRadioButtonActionPerformed
        
        if(priceBilsheRadioButton.isSelected()){
            
            connectionDataBase.connect();
            requestDataBase = new RequestDataBase(connectionDataBase.getConnection());
            
            merchTableModel = new MerchTableModel();
            table.setModel(merchTableModel);
            merchTableModel.refreshData(requestDataBase.getAllMerchPriceDESC());
            
        } else if(priceBilsheRadioButton.isSelected() && countMensheRadioButton.isSelected()) {
            
            connectionDataBase.connect();
            requestDataBase = new RequestDataBase(connectionDataBase.getConnection());
            
            merchTableModel = new MerchTableModel();
            table.setModel(merchTableModel);
            merchTableModel.refreshData(requestDataBase.getAllMerchPriceDescAndCountAsc());
            
        } else if (priceBilsheRadioButton.isSelected() && countBilsheRadioButton.isSelected()) {
            
            connectionDataBase.connect();
            requestDataBase = new RequestDataBase(connectionDataBase.getConnection());
            
            merchTableModel = new MerchTableModel();
            table.setModel(merchTableModel);
            merchTableModel.refreshData(requestDataBase.getAllMerchPriceDescAndCountDesc());
        }
        
    }//GEN-LAST:event_priceBilsheRadioButtonActionPerformed

    private void countMensheRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countMensheRadioButtonActionPerformed
        if (countMensheRadioButton.isSelected()) {
            
            connectionDataBase.connect();
            requestDataBase = new RequestDataBase(connectionDataBase.getConnection());
            
            merchTableModel = new MerchTableModel();
            table.setModel(merchTableModel);
            merchTableModel.refreshData(requestDataBase.getAllMerchCountASC());
            
        }else if (countMensheRadioButton.isSelected() && priceMensheRadioButton.isSelected()) {
            
            connectionDataBase.connect();
            requestDataBase = new RequestDataBase(connectionDataBase.getConnection());
            
            merchTableModel = new MerchTableModel();
            table.setModel(merchTableModel);
            merchTableModel.refreshData(requestDataBase.getAllMerchCountAndPriceASC());
            
        }else if (countMensheRadioButton.isSelected() && priceBilsheRadioButton.isSelected()) {
            
            connectionDataBase.connect();
            requestDataBase = new RequestDataBase(connectionDataBase.getConnection());
            
            merchTableModel = new MerchTableModel();
            table.setModel(merchTableModel);
            merchTableModel.refreshData(requestDataBase.getAllMerchPriceASCandCountDESC());
        }
    }//GEN-LAST:event_countMensheRadioButtonActionPerformed

    private void countBilsheRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countBilsheRadioButtonActionPerformed
        if (countBilsheRadioButton.isSelected()) {
            
            connectionDataBase.connect();
            requestDataBase = new RequestDataBase(connectionDataBase.getConnection());
            
            merchTableModel = new MerchTableModel();
            table.setModel(merchTableModel);
            merchTableModel.refreshData(requestDataBase.getAllMerchCountDesc());
            
        }else if (countBilsheRadioButton.isSelected() && priceMensheRadioButton.isSelected()) {
            
            connectionDataBase.connect();
            requestDataBase = new RequestDataBase(connectionDataBase.getConnection());
            
            merchTableModel = new MerchTableModel();
            table.setModel(merchTableModel);
            merchTableModel.refreshData(requestDataBase.getAllMerchPriceDescAndCountAsc());
            
        }else if (countBilsheRadioButton.isSelected() && priceBilsheRadioButton.isSelected()) {
            connectionDataBase.connect();
            requestDataBase = new RequestDataBase(connectionDataBase.getConnection());
            
            merchTableModel = new MerchTableModel();
            table.setModel(merchTableModel);
            merchTableModel.refreshData(requestDataBase.getAllMerchPriceDescAndCountDesc());
        }
    }//GEN-LAST:event_countBilsheRadioButtonActionPerformed

    private void saleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleButtonActionPerformed
        if(table.getSelectedRow() != -1){
            
            connectionDataBase.connect();
            requestDataBase = new RequestDataBase(connectionDataBase.getConnection());
            
            Object o = new Object();

            o = table.getModel().getValueAt(table.getSelectedRow(), 0);
            merch.setId(Integer.valueOf(o.toString()));
            
            saleFormUI = new SaleFormUI(merch.getId());
            saleFormUI.setVisible(rootPaneCheckingEnabled);
            
        }else JOptionPane.showMessageDialog(null, "Невибраниий товар");
    }//GEN-LAST:event_saleButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> categoryList;
    private javax.swing.JButton clearFilterButton;
    private javax.swing.JRadioButton countBilsheRadioButton;
    private javax.swing.JRadioButton countMensheRadioButton;
    private javax.swing.ButtonGroup countbuttonGroup;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton priceBilsheRadioButton;
    private javax.swing.JRadioButton priceMensheRadioButton;
    private javax.swing.ButtonGroup pricebuttonGroup;
    private javax.swing.JButton saleButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
